name: AnimalProtect
main: de.Fear837.Main
version: 0.1
author: fear837
website: www.youtube.com/fear837
commands:
   lockanimal:
      description: Sichert ein Entity in die Datenbank.
      usage: Write /<command>
      permission: animalprotect.protect
      permission-message: You don't have permission.
      
permissions:
  animalprotect.protect:
    default: true
    description: desc.