name: AnimalProtect
main: de.AnimalProtect.Main
version: 1.0
authors: [Fear837, Pingebam]
website: www.craftolution.de
commands:
   lockanimal:
      description: Sichert ein Entity in die Datenbank.
      usage: Write /<command>
      permission: animalprotect.protect
      permission-message: You don't have permission.
   unlockanimal:
      description: Entsichert ein Entity aus der Datenbank.
      usage: Write /<command>
      permission: animalprotect.protect
      permission-message: You don't have permission.
   lockinfo:
      description: Gibt Informationen ueber ein Entity.
      usage: Write /<command>
      permission: animalprotect.protect
      permission-message: You don't have permission.
   locklist:
      description: Listet alle Tiere die der Person gehoeren auf.
      usage: Write /<command> [playername]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   lockrespawn:
      description: Spawnt das ausgewaehlte Tier neu.
      usage: Write /<command> [id] [owner]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   locktp:
      description: Teleportiert dich zu einem Tier.
      usage: Write /<command> [id] [owner]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   lockdebug:
      description: Gibt Debug-Informationen ueber das Plugin aus.
      usage: Write /<command>
      permission-message: You don't have permission.
   locklimit:
      description: Gibt die Anzahl der Locks ueber einen Spieler aus.
      usage: Write /<command> <name>
      permission: animalprotect.protect
      permission-message: You don't have permission.
   ap:
      description: Gesamtuebersicht aller AnimalProtect-Befehle.
      usage: Write /<command>
      permission: animalprotect.protect
      permission-message: You don't have permission.
permissions:
  animalprotect.protect:
    default: true
    description: desc.
  animalprotect.bypass:
    default: false
    description: desc.
  animalprotect.admin:
    default: false
    description: desc.