database:
  hostname: 'localhost'
  username: 'username'
  password: 'password'
  dbname: 'localhost'
  port: '3306'
settings:
  max_entities_for_player: 25
  debug-messages: true
  worldname: 'Craftolution-de'
messages:
  LOCK_SUCCESS: '%aDas Tier wurde erfolgreich gesichert.'
  LOCK_FAILED: '%cFehler: Das Tier konnte nicht gesichert werden.'
  MAX_LOCKS_EXCEEDED: '%cFehler: Du hast das Limit an Tier-Protections erreicht. (Maximal 50)'
  