name: AnimalProtect
main: de.AnimalProtect.AnimalProtect
version: 1.2

description: Bietet normalen Spielern auf einem Server an, Tiere vor anderen Spielern zu protecten.
authors: [Fear837, Pingebam]
website: www.craftolution.de
loadbefore: [CraftoPlugin]
depend: [CraftoPlugin]
default-permission: animalprotect.protect

commands:
   ap:
      description: Gesamtuebersicht aller AnimalProtect-Befehle.
      usage: Schreibe /ap <befehl>
      permission: animalprotect.protect
      permission-message: You don't have permission.
      aliases: [animalprotect]
   lockanimal:
      description: Sichert ein Tier vor anderen Spielern.
      usage: Schreibe /lockanimal
      permission: animalprotect.protect
      permission-message: You don't have permission.
   unlockanimal:
      description: Entsichert das Tier.
      usage: Schreibe /unlockanimal
      permission: animalprotect.protect
      permission-message: You don't have permission.
   animalinfo:
      description: Gibt Informationen uber das ausgewaehlte Tier aus.
      usage: Schreibe /animalinfo
      permission: animalprotect.protect
      permission-message: You don't have permission.
   listanimals:
      description: Listet alle Tiere die der Person gehoeren auf.
      usage: Schreibe /listanimals [playername] [seite]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   respawnanimal:
      description: Spawnt das ausgewaehlte Tier neu.
      usage: Schreibe /respawnanimal [owner] [id]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   tpanimal:
      description: Teleportiert dich zu einem Tier.
      usage: Schreibe /tpanimal [owner] [id]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   animaldebug:
      description: Gibt Debug-Informationen ueber das Plugin aus.
      usage: Schreibe /animaldebug
      permission: animalprotect.admin
      permission-message: You don't have permission.
   lockedanimals:
      description: Gibt die Anzahl der Locks ueber einen Spieler aus.
      usage: Schreibe /lockedanimals <spieler>
      permission: animalprotect.protect
      permission-message: You don't have permission.

permissions:
  animalprotect.protect:
    default: true
    description: Erlaubt dem Spieler allgemeine AnimalProtect-Befehle zu nutzen.
  animalprotect.bypass:
    default: false
    description: Erlaubt dem Spieler alle Protections von Tieren zu umgehen.
  animalprotect.admin:
    default: false
    description: Erlaubt dem Spieler alle Admin-Befehle von AnimalProtect zu nutzen.