name: AnimalProtect
main: de.AnimalProtect.AnimalProtect
version: 1.2

description: Bietet normalen Spielern auf einem Server an Tiere vor anderen Spielern zu protecten
authors: [Fear837, Pingebam]
website: www.craftolution.de
loadbefore: [CraftoPlugin]
depend: [CraftoPlugin]
default-permission: animalprotect.protect

commands:
   ap:
      description: Gesamtuebersicht aller AnimalProtect-Befehle.
      usage: Schreibe /ap <befehl>
      permission: animalprotect.protect
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [animalprotect]
   lockanimal:
      description: Sichert ein Tier vor anderen Spielern.
      usage: Schreibe /lockanimal
      permission: animalprotect.lock
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [protectanimal]
   unlockanimal:
      description: Entsichert das Tier.
      usage: Schreibe /unlockanimal
      permission: animalprotect.protect
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
   animalinfo:
      description: Gibt Informationen uber das ausgewaehlte Tier aus.
      usage: Schreibe /animalinfo
      permission: animalprotect.protect
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [lockinfo]
   listanimals:
      description: Listet alle Tiere die der Person gehoeren auf.
      usage: Schreibe /listanimals [owner] [seite]
      permission: animalprotect.admin
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [locklist]
   respawnanimal:
      description: Spawnt das ausgewaehlte Tier neu.
      usage: Schreibe /respawnanimal [p:<owner>] [id:<animal-id>] [start:<start-id>] [end:<end-id>] [-missing] [-location]
      permission: animalprotect.admin
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [lockrespawn]
   tpanimal:
      description: Teleportiert dich zu einem Tier.
      usage: Schreibe /tpanimal [owner] [id]
      permission: animalprotect.admin
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [locktp]
   animaldebug:
      description: Gibt Debug-Informationen ueber das Plugin aus.
      usage: Schreibe /animaldebug
      permission: animalprotect.admin
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [lockdebug]
   animalqueue:
      description: Gibt Debug-Informationen ueber die Queue des Plugins aus.
      usage: Schreibe /animalqueue [start/stop]
      permission: animalprotect.admin
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [lockqueue]
   lockedanimals:
      description: Gibt die Anzahl der Locks ueber einen Spieler aus.
      usage: Schreibe /lockedanimals <spieler>
      permission: animalprotect.protect
      permission-message: 'Du hast nicht genuegend Rechte fuer diesen Befehl.'
      aliases: [locklimit]
permissions:
  animalprotect.protect:
    default: true
    description: Erlaubt dem Spieler allgemeine AnimalProtect-Befehle zu nutzen.
  animalprotect.lock:
    default: true
    description: Erlaubt es dem Spieler neue Tiere zu locken.
  animalprotect.bypass:
    default: false
    description: Erlaubt dem Spieler alle Protections von Tieren zu umgehen.
    children:
       animalprotect.protect: true
  animalprotect.admin:
    default: false
    description: Erlaubt dem Spieler alle Admin-Befehle von AnimalProtect zu nutzen.
    children:
       animalprotect.protect: true
       animalprotect.lock: true
       animalprotect.bypass: true