name: AnimalProtect
main: de.AnimalProtect.AnimalProtect
version: 1.2

description: Bietet normalen Spielern auf einem Server an, Tiere vor anderen Spielern zu protecten.
authors: [Fear837, Pingebam]
website: www.craftolution.de
loadbefore: [CraftoPlugin]
depend: [CraftoPlugin]
default-permission: animalprotect.protect

commands:
   lockanimal:
      description: Sichert ein Tier vor anderen Spielern.
      usage: Schreibe /lockanimal
      permission: animalprotect.protect
      permission-message: You don't have permission.
   unlockanimal:
      description: Entsichert das Tier.
      usage: Schreibe /unlockanimal
      permission: animalprotect.protect
      permission-message: You don't have permission.
   lockinfo:
      description: Gibt Informationen uber das ausgewaehlte Tier aus.
      usage: Schreibe /lockinfo
      permission: animalprotect.protect
      permission-message: You don't have permission.
   locklist:
      description: Listet alle Tiere die der Person gehoeren auf.
      usage: Schreibe /locklist [playername] [seite]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   lockrespawn:
      description: Spawnt das ausgewaehlte Tier neu.
      usage: Schreibe /lockrespawn [owner] [id]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   locktp:
      description: Teleportiert dich zu einem Tier.
      usage: Schreibe /locktp [owner] [id]
      permission: animalprotect.admin
      permission-message: You don't have permission.
   lockdebug:
      description: Gibt Debug-Informationen ueber das Plugin aus.
      usage: Schreibe /lockdebug
      permission: animalprotect.admin
      permission-message: You don't have permission.
   locklimit:
      description: Gibt die Anzahl der Locks ueber einen Spieler aus.
      usage: Schreibe /locklimit <spieler>
      permission: animalprotect.protect
      permission-message: You don't have permission.
   ap:
      description: Gesamtuebersicht aller AnimalProtect-Befehle.
      usage: Schreibe /ap <befehl>
      permission: animalprotect.protect
      permission-message: You don't have permission.
      aliases: [animalprotect]

permissions:
  animalprotect.protect:
    default: true
    description: Erlaubt dem Spieler allgemeine AnimalProtect-Befehle zu nutzen.
  animalprotect.bypass:
    default: false
    description: Erlaubt dem Spieler alle Protections von Tieren zu umgehen.
  animalprotect.admin:
    default: false
    description: Erlaubt dem Spieler alle Admin-Befehle von AnimalProtect zu nutzen.